# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Jason\Desktop\github\nixie-psoc-project\nixie_control.cydsn\nixie_control.cyprj
# Date: Sun, 15 May 2022 21:14:58 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyWCO} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/wco}]]
create_clock -name {CyLFCLK} -period 30517.578125 -waveform {0 15258.7890625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyIMO} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 20.8333333333333} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\Jason\Desktop\github\nixie-psoc-project\nixie_control.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Jason\Desktop\github\nixie-psoc-project\nixie_control.cydsn\nixie_control.cyprj
# Date: Sun, 15 May 2022 21:14:54 GMT
