/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "C.h"
#include "C_aliases.h"
#include "B.h"
#include "B_aliases.h"
#include "D.h"
#include "D_aliases.h"
#include "A.h"
#include "A_aliases.h"
#include "E.h"
#include "E_aliases.h"
#include "F.h"
#include "F_aliases.h"
#include "G.h"
#include "G_aliases.h"
#include "H.h"
#include "H_aliases.h"
#include "RTC.h"
#include "I.h"
#include "I_aliases.h"
#include "J.h"
#include "J_aliases.h"
#include "K.h"
#include "K_aliases.h"
#include "L.h"
#include "L_aliases.h"
#include "M.h"
#include "M_aliases.h"
#include "N.h"
#include "N_aliases.h"
#include "O.h"
#include "O_aliases.h"
#include "P.h"
#include "P_aliases.h"
#include "Q.h"
#include "Q_aliases.h"
#include "R.h"
#include "R_aliases.h"
#include "S.h"
#include "S_aliases.h"
#include "T.h"
#include "T_aliases.h"
#include "U.h"
#include "U_aliases.h"
#include "V.h"
#include "V_aliases.h"
#include "W.h"
#include "W_aliases.h"
#include "X.h"
#include "X_aliases.h"
#include "PB.h"
#include "PB_aliases.h"
#include "led.h"
#include "led_aliases.h"
#include "Timer.h"
#include "led_4.h"
#include "led_4_aliases.h"
#include "led_red.h"
#include "led_red_aliases.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "Clock_1.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

